# Generated by Django 4.2.3 on 2023-07-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Student'), (2, 'Staff'), (3, 'Parent')], default=1, null=True),
        ),
    ]
