# Generated by Django 4.2.3 on 2023-07-21 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClassManagement', '0001_initial'),
        ('CustomUser', '0003_alter_users_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='DOB',
            field=models.DateField(default='1998-01-01'),
        ),
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('Others', 'Others')], default='Male', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=2),
        ),
        migrations.AddField(
            model_name='users',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='users', to='ClassManagement.class'),
        ),
    ]
