# Generated by Django 4.2.3 on 2023-07-21 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='subjectscreated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.CharField(max_length=100, primary_key='True', serialize=False)),
                ('std', models.IntegerField()),
                ('section', models.CharField(max_length=100)),
                ('createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='classcreated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
