# Generated by Django 4.2.3 on 2023-07-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='class',
            name='section',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
